name: LuaJIT-Main

on:
  workflow_dispatch:
  push:
    branches:
      - 'v2.1'
  pull_request:
    branches: [ v2.1 ]


jobs:
  Build-Release:
    strategy:
      matrix:
        target_system: [ ubuntu-22.04, windows-2022 ]
    runs-on: ${{ matrix.target_system }}
    env:
      BUILD_EXT_DYN: ${{ matrix.target_system == 'windows-2022' && '.dll' || '.so' }}
      BUILD_EXT_STAT: ${{ matrix.target_system == 'windows-2022' && '.lib' || '.a' }}
      BUILD_PREFIX: ${{ matrix.target_system != 'windows-2022' && 'lib' || ''}}
      
      BUILD_DIR: D:/a/LuaJIT/LuaJIT/lib/
      # LIB_NAME:

    steps:
      - uses: actions/checkout@v4

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: runner.os == 'Windows'
        with:
          arch: x64

      - name: Build
        run: |
          ${{ runner.os != 'Windows' && 'make' || 'cd src && ./msvcbuild.bat && cd ..'}}
          # ls -la

      - name: Make Archive
        # if: github.event_name != 'pull_request'
        run: |
          ${{ runner.os == 'Windows' && 'md' || 'mkdir' }} bin include lib lua
          cd src
          mv jit ../lua
          mv ${{ env.BUILD_PREFIX }}luajit${{ env.BUILD_EXT_DYN }} ../bin
          mv ${{ env.BUILD_PREFIX }}luajit${{ env.BUILD_EXT_STAT }} ../lib
          mv lauxlib.h lua.h lua.hpp luaconf.h luajit.h lualib.h ../include
          cd ..
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on LuaJIT-${{ runner.os }}-.7z COPYRIGHT bin include lib lua README


      - name: Upload Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Stable-CI
          files: LuaJIT-${{ runner.os }}-.7z
          body: |
            CI Build for Dreamweave LuaJIT Fork

      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: |
            COPYRIGHT
            bin
            include
            lib
            lua
            README
          name: LuaJIT-${{ runner.os }}
